version: "3"

services:
  db:
    container_name: Reception-Register-DB
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "27017:27017"
    image: mongo:latest
    restart: always
    volumes:
      - ./mongodb/db:/data/db
  api:
    build: ./reception_register_api
    command: bash -c "npm run build && npm start bootstrap"
    container_name: Reception-Register-API
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: reception-register:api
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - /reception-register/node_modules
      - ./reception_register_api:/reception-register
  webui:
    build: ./reception_register_webui
    command: npm run build
    container_name: Reception-Register-Web-UI
    depends_on:
      - db
    image: reception-register:webui
    volumes:
      - /reception-register/node_modules
      - ./reception_register_webui:/reception-register
  proxy:
    container_name: Reception-Register-Proxy
    depends_on:
      - api
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs
      - ./reception_register_webui/dist:/var/www/html
